# Deploymenty Configuration for Auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  # Find all pods with the label 'app: pods' that the deployment will create
  selector:
    matchLabels:
      app: payments
  # How to create each individual pod that the deployment will create
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments  # This name is only important for logging purposes
          image: ejun3227/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# Cluster IP Service Configuration for Auth
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000