# Deploymenty Configuration for Auth
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  # Find all pods with the label 'app: pods' that the deployment will create
  selector:
    matchLabels:
      app: tickets
  # How to create each individual pod that the deployment will create
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets  # This name is only important for logging purposes
          image: ejun3227/tickets
          env:
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
              
---
# Cluster IP Service Configuration for Auth
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000